(() => {
  'use strict';
  const KEY='pyc_language_v1';
  const labels={ca:'Català',es:'Castellano',en:'English',fr:'Français',de:'Deutsch',ru:'Русский',pt:'Português'};
  const d={
    ca:{language:'Idioma',home:'Inici',clients:'Clients',cases:'Expedients',billing:'Facturació',quality:'Qualitat',loadDemo:'Carregar demo',newClient:'Nou client',newCase:'Nou expedient',newInvoice:'Nova factura',newProvision:'Nova provisió',search:'Cerca',invoices:'Factures',provisions:'Provisions',audit:'Auditoria',runAll:'Executar totes',docLanguage:'Idioma del document',copyLanguage:'Idioma de la còpia',generateCopy:'Generar còpia',documentPreview:'Previsualització del document',invoice:'FACTURA',issueDate:'Data d’emissió',taxBase:'Base imposable',vat:'IVA',total:'TOTAL',noClients:'No hi ha clients.',noCases:'No hi ha expedients.',noInvoices:'No hi ha factures.',noProvisions:'No hi ha provisions.',noTaxId:'Sense NIF',noCode:'Sense codi',noNumber:'Sense número',draft:'esborrany',pending:'pendent',createClientFirst:'Crea primer un client.',createCaseFirst:'Crea primer un expedient.'},
    es:{language:'Idioma',home:'Inicio',clients:'Clientes',cases:'Expedientes',billing:'Facturación',quality:'Calidad',loadDemo:'Cargar demo',newClient:'Nuevo cliente',newCase:'Nuevo expediente',newInvoice:'Nueva factura',newProvision:'Nueva provisión',search:'Buscar',invoices:'Facturas',provisions:'Provisiones',audit:'Auditoría',runAll:'Ejecutar todas',docLanguage:'Idioma del documento',copyLanguage:'Idioma de la copia',generateCopy:'Generar copia',documentPreview:'Vista previa del documento',invoice:'FACTURA',issueDate:'Fecha de emisión',taxBase:'Base imponible',vat:'IVA',total:'TOTAL',noClients:'No hay clientes.',noCases:'No hay expedientes.',noInvoices:'No hay facturas.',noProvisions:'No hay provisiones.',noTaxId:'Sin NIF',noCode:'Sin código',noNumber:'Sin número',draft:'borrador',pending:'pendiente',createClientFirst:'Crea primero un cliente.',createCaseFirst:'Crea primero un expediente.'},
    en:{language:'Language',home:'Home',clients:'Clients',cases:'Matters',billing:'Billing',quality:'Quality',loadDemo:'Load demo',newClient:'New client',newCase:'New matter',newInvoice:'New invoice',newProvision:'New retainer',search:'Search',invoices:'Invoices',provisions:'Retainers',audit:'Audit',runAll:'Run all',docLanguage:'Document language',copyLanguage:'Copy language',generateCopy:'Generate copy',documentPreview:'Document preview',invoice:'INVOICE',issueDate:'Issue date',taxBase:'Taxable amount',vat:'VAT',total:'TOTAL',noClients:'No clients.',noCases:'No matters.',noInvoices:'No invoices.',noProvisions:'No retainers.',noTaxId:'No tax ID',noCode:'No code',noNumber:'No number',draft:'draft',pending:'pending',createClientFirst:'Create a client first.',createCaseFirst:'Create a matter first.'},
    fr:{language:'Langue',home:'Accueil',clients:'Clients',cases:'Dossiers',billing:'Facturation',quality:'Qualité',loadDemo:'Charger la démo',newClient:'Nouveau client',newCase:'Nouveau dossier',newInvoice:'Nouvelle facture',newProvision:'Nouvelle provision',search:'Rechercher',invoices:'Factures',provisions:'Provisions',audit:'Audit',runAll:'Tout exécuter',docLanguage:'Langue du document',copyLanguage:'Langue de la copie',generateCopy:'Générer la copie',documentPreview:'Aperçu du document',invoice:'FACTURE',issueDate:'Date d’émission',taxBase:'Base imposable',vat:'TVA',total:'TOTAL',noClients:'Aucun client.',noCases:'Aucun dossier.',noInvoices:'Aucune facture.',noProvisions:'Aucune provision.',noTaxId:'Sans identifiant fiscal',noCode:'Sans code',noNumber:'Sans numéro',draft:'brouillon',pending:'en attente',createClientFirst:'Créez d’abord un client.',createCaseFirst:'Créez d’abord un dossier.'},
    de:{language:'Sprache',home:'Start',clients:'Mandanten',cases:'Akten',billing:'Abrechnung',quality:'Qualität',loadDemo:'Demo laden',newClient:'Neuer Mandant',newCase:'Neue Akte',newInvoice:'Neue Rechnung',newProvision:'Neuer Vorschuss',search:'Suchen',invoices:'Rechnungen',provisions:'Vorschüsse',audit:'Prüfung',runAll:'Alle ausführen',docLanguage:'Dokumentsprache',copyLanguage:'Sprache der Kopie',generateCopy:'Kopie erstellen',documentPreview:'Dokumentvorschau',invoice:'RECHNUNG',issueDate:'Ausstellungsdatum',taxBase:'Nettobetrag',vat:'MwSt.',total:'GESAMT',noClients:'Keine Mandanten.',noCases:'Keine Akten.',noInvoices:'Keine Rechnungen.',noProvisions:'Keine Vorschüsse.',noTaxId:'Ohne Steuer-ID',noCode:'Ohne Code',noNumber:'Ohne Nummer',draft:'Entwurf',pending:'ausstehend',createClientFirst:'Erstellen Sie zuerst einen Mandanten.',createCaseFirst:'Erstellen Sie zuerst eine Akte.'},
    ru:{language:'Язык',home:'Главная',clients:'Клиенты',cases:'Дела',billing:'Счета',quality:'Качество',loadDemo:'Загрузить демо',newClient:'Новый клиент',newCase:'Новое дело',newInvoice:'Новый счёт',newProvision:'Новый аванс',search:'Поиск',invoices:'Счета',provisions:'Авансы',audit:'Аудит',runAll:'Запустить все',docLanguage:'Язык документа',copyLanguage:'Язык копии',generateCopy:'Создать копию',documentPreview:'Предпросмотр документа',invoice:'СЧЁТ',issueDate:'Дата выставления',taxBase:'Налоговая база',vat:'НДС',total:'ИТОГО',noClients:'Нет клиентов.',noCases:'Нет дел.',noInvoices:'Нет счетов.',noProvisions:'Нет авансов.',noTaxId:'Без ИНН',noCode:'Без кода',noNumber:'Без номера',draft:'черновик',pending:'ожидает',createClientFirst:'Сначала создайте клиента.',createCaseFirst:'Сначала создайте дело.'},
    pt:{language:'Idioma',home:'Início',clients:'Clientes',cases:'Processos',billing:'Faturação',quality:'Qualidade',loadDemo:'Carregar demo',newClient:'Novo cliente',newCase:'Novo processo',newInvoice:'Nova fatura',newProvision:'Nova provisão',search:'Pesquisar',invoices:'Faturas',provisions:'Provisões',audit:'Auditoria',runAll:'Executar todas',docLanguage:'Idioma do documento',copyLanguage:'Idioma da cópia',generateCopy:'Gerar cópia',documentPreview:'Pré-visualização do documento',invoice:'FATURA',issueDate:'Data de emissão',taxBase:'Base tributável',vat:'IVA',total:'TOTAL',noClients:'Não há clientes.',noCases:'Não há processos.',noInvoices:'Não há faturas.',noProvisions:'Não há provisões.',noTaxId:'Sem NIF',noCode:'Sem código',noNumber:'Sem número',draft:'rascunho',pending:'pendente',createClientFirst:'Crie primeiro um cliente.',createCaseFirst:'Crie primeiro um processo.'}
  };
  const lang=()=>labels[localStorage.getItem(KEY)]?localStorage.getItem(KEY):'ca';
  const t=k=>d[lang()]?.[k]||d.ca[k]||k;
  function apply(){document.documentElement.lang=lang();document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));const s=document.getElementById('languageSelector');if(s)s.value=lang();window.PYC?.render?.();window.PYCDocUI?.renderPreview?.();}
  function setLanguage(v){if(!labels[v])return;localStorage.setItem(KEY,v);apply();}
  window.PYCI18N={labels,d,t,lang,setLanguage,applyTranslations:apply};
})();