(() => {
  'use strict';
  const VERSION='v0.2.1-dev.36',KEY='pyc_office_v2',$=id=>document.getElementById(id),uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,round=n=>Math.round((Number(n||0)+Number.EPSILON)*100)/100,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),t=k=>window.PYCI18N?.t(k)||k;
  const empty=()=>({version:3,build:VERSION,settings:{invoicePrefix:'F-2026-',nextInvoiceNumber:1},clients:[],cases:[],documents:[],serviceCatalog:[],provisions:[],payments:[],activity:[]});
  const load=()=>{try{return{...empty(),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})}}catch{return empty()}};
  const save=s=>{s.version=3;s.build=VERSION;localStorage.setItem(KEY,JSON.stringify(s));render()};
  const modal=(title,body,actions='')=>{$('appModal').innerHTML=`<div class="modal"><div class="sheet"><div class="sheet-head"><h3>${esc(title)}</h3><button class="icon-btn" onclick="PYC.closeModal()">×</button></div><div class="sheet-body">${body}<div class="sheet-actions">${actions}</div></div></div></div>`};
  const closeModal=()=>{$('appModal').innerHTML=''};
  const row=(title,meta,onClick)=>`<button class="row row-button" type="button" data-action="${onClick}"><div><strong>${esc(title)}</strong><div class="label">${esc(meta)}</div></div><span>›</span></button>`;
  function render(){const s=load(),inv=s.documents.filter(d=>d.type==='factura');$('mClients').textContent=s.clients.length;$('mCases').textContent=s.cases.length;$('mInvoices').textContent=inv.length;$('mProvisions').textContent=`${round(s.provisions.reduce((a,p)=>a+(p.availableAmount||0),0)).toFixed(2)} €`;const q=($('clientSearch').value||'').toLowerCase();$('clientList').innerHTML=s.clients.filter(c=>`${c.name} ${c.tax||''}`.toLowerCase().includes(q)).map(c=>row(c.name,c.tax||t('noTaxId'),`edit-client:${c.id}`)).join('')||`<div class="status">${esc(t('noClients'))}</div>`;$('caseList').innerHTML=s.cases.map(c=>row(c.name,c.code||t('noCode'),`edit-case:${c.id}`)).join('')||`<div class="status">${esc(t('noCases'))}</div>`;$('invoiceList').innerHTML=inv.map(i=>row(i.number||t('noNumber'),`${Number(i.total||0).toFixed(2)} € · ${i.status||t('draft')} · ${(i.lines||[]).length} línies`,`edit-invoice:${i.id}`)).join('')||`<div class="status">${esc(t('noInvoices'))}</div>`;$('provisionList').innerHTML=s.provisions.map(p=>row(p.title||t('provisions'),`${Number(p.availableAmount||0).toFixed(2)} € · ${p.status||t('pending')}`,`edit-provision:${p.id}`)).join('')||`<div class="status">${esc(t('noProvisions'))}</div>`}
  function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));sessionStorage.setItem('pyc_unified_view',name)}
  function clientForm(id=null){const s=load(),c=id?s.clients.find(x=>x.id===id):null;modal(c?'Editar client':t('newClient'),`<div class="field"><label>Nom</label><input id="fClientName" value="${esc(c?.name||'')}"></div><div class="field"><label>NIF</label><input id="fClientTax" value="${esc(c?.tax||'')}"></div><div class="field"><label>Email</label><input id="fClientEmail" type="email" value="${esc(c?.email||'')}"></div><div class="field"><label>Telèfon</label><input id="fClientPhone" value="${esc(c?.phone||'')}"></div><div class="field"><label>Idioma preferit</label><select id="fClientLanguage">${Object.entries(PYCI18N.labels).map(([k,v])=>`<option value="${k}" ${k===(c?.preferredLanguage||PYCI18N.lang())?'selected':''}>${v}</option>`).join('')}</select></div>`,`${c?'<button class="btn danger" onclick="PYC.deleteClient(\''+c.id+'\')">Eliminar</button>':''}<button class="btn" onclick="PYC.closeModal()">Cancel·lar</button><button class="btn primary" onclick="PYC.saveClient('${c?.id||''}')">Desar</button>`)}
  function saveClient(id=''){const s=load(),data={name:$('fClientName').value.trim(),tax:$('fClientTax').value.trim(),email:$('fClientEmail').value.trim(),phone:$('fClientPhone').value.trim(),preferredLanguage:$('fClientLanguage').value};if(!data.name)return alert('El nom és obligatori.');if(data.tax&&s.clients.some(c=>c.id!==id&&c.tax?.toLowerCase()===data.tax.toLowerCase()))return alert('Aquest NIF ja existeix.');if(id)Object.assign(s.clients.find(c=>c.id===id),data);else s.clients.push({id:uid(),...data});save(s);closeModal()}
  function deleteClient(id){const s=load();if(s.cases.some(c=>c.participants?.some(p=>p.clientId===id)))return alert('No es pot eliminar: el client està vinculat a un expedient.');s.clients=s.clients.filter(c=>c.id!==id);save(s);closeModal()}
  function invoiceLinesMarkup(lines){return `<div id="invoiceLines">${lines.map((l,i)=>`<div class="invoice-line" data-line-index="${i}"><div class="field"><label>Concepte</label><input class="line-concept" value="${esc(l.concept||'')}"></div><div class="field"><label>Descripció</label><input class="line-description" value="${esc(l.description||'')}"></div><div class="line-grid"><div class="field"><label>Quantitat</label><input class="line-qty" type="number" min="0" step="0.01" value="${Number(l.qty||1)}"></div><div class="field"><label>Preu unitari</label><input class="line-price" type="number" step="0.01" value="${Number(l.price||0)}"></div><div class="field"><label>IVA %</label><input class="line-vat" type="number" step="0.01" value="${Number(l.vat??21)}"></div><button type="button" class="btn danger line-remove" ${lines.length===1?'disabled':''}>Eliminar línia</button></div></div>`).join('')}</div><button type="button" id="addInvoiceLine" class="btn">+ Afegir línia</button><div id="invoiceTotals" class="status" style="margin-top:12px"></div>`}
  function invoiceForm(id=null){const s=load();if(!s.cases.length)return alert(t('createCaseFirst'));const i=id?s.documents.find(x=>x.id===id):null,caseId=i?.caseId||s.cases[0].id,status=i?.status||'esborrany',lines=(i?.lines?.length?i.lines:[{id:uid(),concept:'Honoraris professionals',description:'',qty:1,price:100,vat:21}]).map(x=>({...x}));modal(i?'Editar factura':t('newInvoice'),`<div class="field"><label>Expedient</label><select id="fInvoiceCase">${s.cases.map(c=>`<option value="${c.id}" ${c.id===caseId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Estat</label><select id="fInvoiceStatus"><option value="esborrany" ${status==='esborrany'?'selected':''}>Esborrany</option><option value="emesa" ${status==='emesa'?'selected':''}>Emesa</option><option value="pagada" ${status==='pagada'?'selected':''}>Pagada</option><option value="anul·lada" ${status==='anul·lada'?'selected':''}>Anul·lada</option></select></div><h4>Línies de factura</h4>${invoiceLinesMarkup(lines)}`,`${i?'<button class="btn danger" onclick="PYC.deleteInvoice(\''+i.id+'\')">Eliminar factura</button>':''}<button class="btn" onclick="PYC.closeModal()">Cancel·lar</button><button class="btn primary" onclick="PYC.saveInvoice('${i?.id||''}')">Desar</button>`);bindInvoiceLines();updateInvoiceTotals()}
  function bindInvoiceLines(){const add=$('addInvoiceLine');if(add)add.addEventListener('click',()=>{const c=document.createElement('div');c.innerHTML=invoiceLinesMarkup([{id:uid(),concept:'',description:'',qty:1,price:0,vat:21}]);const line=c.querySelector('.invoice-line');$('invoiceLines').appendChild(line);bindInvoiceLines();updateRemoveStates();updateInvoiceTotals()});document.querySelectorAll('.line-remove').forEach(b=>b.onclick=e=>{e.currentTarget.closest('.invoice-line').remove();updateRemoveStates();updateInvoiceTotals()});document.querySelectorAll('.invoice-line input').forEach(i=>i.oninput=updateInvoiceTotals)}
  function updateRemoveStates(){const lines=[...document.querySelectorAll('.invoice-line')];lines.forEach(l=>l.querySelector('.line-remove').disabled=lines.length===1)}
  function readInvoiceLines(){return [...document.querySelectorAll('.invoice-line')].map(l=>({id:l.dataset.id||uid(),concept:l.querySelector('.line-concept').value.trim(),description:l.querySelector('.line-description').value.trim(),qty:round(l.querySelector('.line-qty').value),price:round(l.querySelector('.line-price').value),vat:round(l.querySelector('.line-vat').value)}))}
  function calcInvoice(lines){const base=round(lines.reduce((a,l)=>a+l.qty*l.price,0)),vat=round(lines.reduce((a,l)=>a+(l.qty*l.price*l.vat/100),0));return{base,vat,total:round(base+vat)}}
  function updateInvoiceTotals(){const box=$('invoiceTotals');if(!box)return;const {base,vat,total}=calcInvoice(readInvoiceLines());box.innerHTML=`Base: <strong>${base.toFixed(2)} €</strong> · IVA: <strong>${vat.toFixed(2)} €</strong> · Total: <strong>${total.toFixed(2)} €</strong>`}
  function saveInvoice(id=''){const s=load(),lines=readInvoiceLines();if(!lines.length)return alert('Afegeix almenys una línia.');if(lines.some(l=>!l.concept||l.qty<=0||l.price<0||l.vat<0))return alert('Revisa les línies de factura.');const totals=calcInvoice(lines),status=$('fInvoiceStatus').value;if(id){const i=s.documents.find(x=>x.id===id);Object.assign(i,{caseId:$('fInvoiceCase').value,status,...totals,amountDue:status==='pagada'?0:totals.total,lines})}else{const seq=Number(s.settings.nextInvoiceNumber||1);s.documents.push({id:uid(),caseId:$('fInvoiceCase').value,type:'factura',number:`${s.settings.invoicePrefix}${String(seq).padStart(3,'0')}`,status,...totals,amountDue:status==='pagada'?0:totals.total,language:PYCI18N.lang(),lines});s.settings.nextInvoiceNumber=seq+1}save(s);closeModal()}
  function deleteInvoice(id){const s=load();s.documents=s.documents.filter(d=>d.id!==id);save(s);closeModal()}
  function addCase(){const s=load();if(!s.clients.length)return alert(t('createClientFirst'));const n=s.cases.length+1;s.cases.push({id:uid(),name:`${t('cases')} ${n}`,code:`EXP-2026-${String(n).padStart(3,'0')}`,participants:[{clientId:s.clients[0].id}],status:'obert'});save(s)}
  function addProvision(){const s=load();if(!s.cases.length)return alert(t('createCaseFirst'));s.provisions.push({id:uid(),caseId:s.cases[0].id,title:t('provisions'),requestedAmount:300,paidAmount:300,availableAmount:300,appliedAmount:0,status:'pagada'});save(s)}
  function loadDemo(){const s=empty();s.clients=[{id:'c1',name:'Anna Garcia',tax:'12345678A',email:'anna@example.com',preferredLanguage:'ca'},{id:'c2',name:'Marc Pérez',tax:'87654321B',preferredLanguage:'es'}];s.cases=[{id:'e1',name:'Divorci Garcia - Pérez',code:'EXP-2026-001',participants:[{clientId:'c1'},{clientId:'c2'}],status:'obert'}];s.documents=[{id:'f1',caseId:'e1',type:'factura',number:'F-2026-001',status:'emesa',base:650,vat:136.5,total:786.5,amountDue:786.5,language:'ca',lines:[{id:'l1',concept:'Conveni regulador',description:'Redacció i revisió',qty:1,price:500,vat:21},{id:'l2',concept:'Reunió jurídica',description:'Sessió de 90 minuts',qty:1.5,price:100,vat:21}]}];s.settings.nextInvoiceNumber=2;s.provisions=[{id:'p1',caseId:'e1',title:'Provisió inicial',requestedAmount:300,paidAmount:300,availableAmount:0,appliedAmount:300,status:'aplicada'}];save(s)}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const [action,id]=b.dataset.action.split(':');if(action==='edit-client')clientForm(id);if(action==='edit-invoice')invoiceForm(id)});document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('loadDemo').addEventListener('click',loadDemo);$('addClient').addEventListener('click',()=>clientForm());$('addCase').addEventListener('click',addCase);$('addInvoice').addEventListener('click',()=>invoiceForm());$('addProvision').addEventListener('click',addProvision);$('clientSearch').addEventListener('input',render);$('languageSelector').addEventListener('change',e=>PYCI18N.setLanguage(e.target.value));showView(sessionStorage.getItem('pyc_unified_view')||'home');render();window.PYC={VERSION,KEY,load,save,empty,render,showView,loadDemo,closeModal,clientForm,saveClient,deleteClient,invoiceForm,saveInvoice,deleteInvoice,addCase,addProvision,round};PYCI18N.applyTranslations();
})();