function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`}

export const DOCUMENT_STATES=Object.freeze({DRAFT:'esborrany',REVIEW:'en_revisio',APPROVED:'aprovat',SIGNED:'signat',ARCHIVED:'arxivat'});

export function createTemplate(state,input){const name=String(input?.name||'').trim();if(!name)throw new Error('El nom de la plantilla és obligatori.');const template={id:uid(),name,documentType:input.documentType||'lliure',language:input.language||'ca',content:String(input.content||''),variables:[...new Set(input.variables||[])],active:input.active!==false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};return{state:{...state,documentTemplates:[...(state.documentTemplates||[]),template]},template}}

export function renderTemplate(template,values={}){let output=String(template?.content||'');(template?.variables||[]).forEach(key=>{const token=new RegExp(`{{\\s*${key}\\s*}}`,'g');output=output.replace(token,String(values[key]??''))});return output}

export function createVersionedDocument(state,input){if(!(state.cases||[]).some(item=>item.id===input.caseId))throw new Error('L’expedient no existeix.');const title=String(input.title||'').trim();if(!title)throw new Error('El títol és obligatori.');const template=input.templateId?(state.documentTemplates||[]).find(item=>item.id===input.templateId):null;if(input.templateId&&!template)throw new Error('La plantilla no existeix.');const now=new Date().toISOString();const content=template?renderTemplate(template,input.variables||{}):String(input.content||'');const version={id:uid(),number:1,content,variables:input.variables||{},createdAt:now,createdBy:input.createdBy||'',note:'Versió inicial'};const document={id:uid(),caseId:input.caseId,type:input.type||template?.documentType||'lliure',title,templateId:template?.id||'',language:input.language||template?.language||'ca',status:DOCUMENT_STATES.DRAFT,currentVersionId:version.id,versions:[version],signature:{required:Boolean(input.signatureRequired),status:input.signatureRequired?'pendent':'no_requerida',signedAt:'',signerIds:[]},facturable:Boolean(input.facturable),invoiceId:'',createdAt:now,updatedAt:now};return{state:{...state,documents:[...(state.documents||[]),document],activity:[...(state.activity||[]),{id:uid(),caseId:document.caseId,title:'Document creat',body:document.title,date:now.slice(0,10)}]},document}}

export function addDocumentVersion(state,documentId,input){const document=(state.documents||[]).find(item=>item.id===documentId);if(!document)throw new Error('No s’ha trobat el document.');if([DOCUMENT_STATES.SIGNED,DOCUMENT_STATES.ARCHIVED].includes(document.status))throw new Error('Un document signat o arxivat no es pot editar.');const now=new Date().toISOString();const version={id:uid(),number:(document.versions||[]).length+1,content:String(input.content??''),variables:input.variables||{},createdAt:now,createdBy:input.createdBy||'',note:String(input.note||'').trim()};const updated={...document,currentVersionId:version.id,versions:[...(document.versions||[]),version],status:DOCUMENT_STATES.DRAFT,updatedAt:now};return{state:{...state,documents:state.documents.map(item=>item.id===documentId?updated:item)},document:updated,version}}

export function transitionDocument(state,documentId,nextState){const allowed={esborrany:['en_revisio','arxivat'],en_revisio:['esborrany','aprovat'],aprovat:['esborrany','signat','arxivat'],signat:['arxivat'],arxivat:[]};const document=(state.documents||[]).find(item=>item.id===documentId);if(!document)throw new Error('No s’ha trobat el document.');if(!(allowed[document.status]||[]).includes(nextState))throw new Error(`Transició no permesa: ${document.status} → ${nextState}.`);if(nextState===DOCUMENT_STATES.SIGNED&&document.signature.required&&document.signature.status!=='completada')throw new Error('La signatura requerida encara no està completada.');const updated={...document,status:nextState,updatedAt:new Date().toISOString()};return{state:{...state,documents:state.documents.map(item=>item.id===documentId?updated:item)},document:updated}}

export function completeSignature(state,documentId,signerIds=[]){const document=(state.documents||[]).find(item=>item.id===documentId);if(!document)throw new Error('No s’ha trobat el document.');if(!document.signature?.required)throw new Error('Aquest document no requereix signatura.');const now=new Date().toISOString();const updated={...document,signature:{...document.signature,status:'completada',signedAt:now,signerIds:[...new Set(signerIds)]},updatedAt:now};return{state:{...state,documents:state.documents.map(item=>item.id===documentId?updated:item)},document:updated}}

export function currentDocumentVersion(document){return(document?.versions||[]).find(version=>version.id===document.currentVersionId)||document?.versions?.at(-1)||null}
